name: Build and Push Docker Image

on:
 pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}" > .env
          echo "NEXT_PUBLIC_WORDPRESS_API_URL=${{ vars.NEXT_PUBLIC_WORDPRESS_API_URL }}" >> .env
          echo "NEXT_PUBLIC_WORDPRESS_API_HOSTNAME=${{ vars.NEXT_PUBLIC_WORDPRESS_API_HOSTNAME }}" >> .env
          echo "HEADLESS_SECRET=${{ secrets.HEADLESS_SECRET }}" >> .env
          echo "WP_USER=${{ secrets.WP_USER }}" >> .env
          echo "WP_APP_PASS=${{ secrets.WP_APP_PASS }}" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            jwhangbo/v2:latest
            jwhangbo/v2:${{ github.sha }}
