name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo environment variables
        run: |
          echo "NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}"
          echo "NEXT_PUBLIC_WORDPRESS_API_URL=${{ vars.NEXT_PUBLIC_WORDPRESS_API_URL }}"
          echo "NEXT_PUBLIC_WORDPRESS_API_HOSTNAME=${{ vars.NEXT_PUBLIC_WORDPRESS_API_HOSTNAME }}"
          # Don't echo actual secrets, just check if they're set

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            jwwhangbo/v2:latest
            jwwhangbo/v2:${{ github.sha }}
          secret-envs: |
            NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_WORDPRESS_API_URL=${{ vars.NEXT_PUBLIC_WORDPRESS_API_URL }}
            NEXT_PUBLIC_WORDPRESS_API_HOSTNAME=${{ vars.NEXT_PUBLIC_WORDPRESS_API_HOSTNAME }}
            HEADLESS_SECRET=${{ secrets.HEADLESS_SECRET }}
            WP_USER=${{ secrets.WP_USER }}
            WP_APP_PASS=${{ secrets.WP_APP_PASS }}
